[env]
TERM = 'xterm-256color'

[font]
size = 14

# Default colors
[colors.primary]
background = '#121314'
foreground = '#B3B1AD'

# Cursor colors
[colors.cursor]
text = '#0A0E14'  # Matches the background color
cursor = '#CCCCCC'

# Normal colors (ansi)
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#CC7CD9'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors (brights)
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

